server:
  port:  ${PORT:${SERVER_PORT:0}}  #0 ->para q me de el primer puerto q no este en uso
eureka:
  client:
    fetch-registry: true
    register-with-eureka:  true #pq son los clientes de eureka se van a registrar
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id:  ${spring.application.name}:${spring.application.instance_id:${random.value}}  #me de una instancia aleotario  

spring:
  application:
    zipkin:  http://localhost:9411
      